In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame([(1,2),(3,5),(2,0),(4,5)],columns=['a1','a2'])

def manhattan_distance(x1,y1,x2,y2):
  return abs(x1-x2)+ abs(y1-y2)

print(df)
print(manhattan_distance(df.iloc[0]['a1'], df.iloc[0]['a2'], df.iloc[1]['a1'], df.iloc[1]['a2']))


   a1  a2
0   1   2
1   3   5
2   2   0
3   4   5
5


# Task 2 nearest neighbor learning with trainning  set in assignment

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
news = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/trainset.txt',sep='\t',names=['CLASS','TITLE','DATE','BODY'])
news.head()

CLASS                                              TITLE  \
0      1   JAPAN FIRM PLANS TO SELL U.S. FARMLAND TO JAP...   
1     -1   NORTH BH SETS ONE-FOR-FIVE OFFER FOR NORGOLD ...   
2     -1    OUTOKUMPU IN COPPER DEAL WITH IBERICA DEL COBRE   
3      1     ROTTERDAM GRAIN HANDLER SAYS PORT BALANCE ROSE   
4      1   U.S. SENATE PANEL VOTES TO LIMIT COUNTY LOAN ...   

                          DATE  \
0   MORIOKA, Japan, March 12 -   
1        MELBOURNE, March 12 -   
2          HELSINKI, June 26 -   
3        ROTTERDAM, April 13 -   
4                    (NO DATE)   

                                                BODY  
0   A Japanese real estate company  said it will ...  
1   North Broken Hill Holdings Ltd  & lt;NBHA.ME ...  
2   Finland's state-owned mining company  Outokum...  
3   Graan Elevator Mij, GEM, said its  balance in...  
4                                          (NO TEXT)

In [49]:
import nltk
nltk.download('all')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-dat

In [50]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

def preprocess(text):
    tokens = word_tokenize(text)
    stop_words = set(stopwords.words('english'))  # Corrected set name to 'english'
    tokens = [token for token in tokens if token.lower() not in stop_words]
    tokens = [token for token in tokens if len(token)>=3]
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token.lower()) for token in tokens]
    return tokens

preprocess(news['BODY'][0])

['japanese',
 'real',
 'estate',
 'company',
 'said',
 'launch',
 'campaign',
 'sell',
 'land',
 'u.s',
 'farming',
 'area',
 'rich',
 'japanese',
 'higashi',
 'nippon',
 'house',
 'said',
 'would',
 'offer',
 'around',
 '2,200',
 'acre',
 'land',
 'illinois',
 'california',
 'florida',
 'indiana',
 'early',
 'april',
 'gauge',
 'response',
 'set',
 'international',
 'farm',
 'corp',
 'america',
 'chicago',
 'last',
 'september',
 'oversee',
 'operation',
 'american',
 'farmer',
 'would',
 'continue',
 'working',
 'tenant',
 'part',
 'profit',
 'harvest',
 'rice',
 'corn',
 'soybean',
 'orange',
 'would',
 'japanese',
 'investor',
 'rental',
 'japanese',
 'agriculture',
 'ministry',
 'official',
 'told',
 'reuters',
 'sale',
 'limited',
 'farmer',
 'keep',
 'land',
 'agricultural',
 'use',
 'two',
 'year',
 'ago',
 'began',
 'seek',
 'farmland',
 'japan',
 'said',
 'isao',
 'nakamura',
 'president',
 'higashi',
 'nippon',
 'however',
 'sale',
 'japanese',
 'farmland',
 'strictly',
 'co

In [51]:
texts = news['BODY']
labels = news['CLASS']

In [52]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(texts)
print(X.toarray())
X.shape

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


(200, 4909)

In [53]:
print(vectorizer.vocabulary_)

{'japanese': 2613, 'real': 3690, 'estate': 1874, 'company': 1293, 'said': 3950, 'it': 2597, 'will': 4826, 'launch': 2716, 'campaign': 1094, 'to': 4517, 'sell': 4018, 'land': 2700, 'in': 2462, 'farming': 1995, 'areas': 775, 'rich': 3880, 'higashi': 2344, 'nippon': 3152, 'house': 2393, 'would': 4862, 'offer': 3197, 'around': 788, '200': 155, 'acres': 579, 'of': 3195, 'illinois': 2429, 'california': 1085, 'florida': 2079, 'and': 719, 'indiana': 2485, 'from': 2149, 'early': 1762, 'april': 768, 'gauge': 2181, 'response': 3842, 'set': 4043, 'up': 4674, 'international': 2553, 'farm': 1992, 'corp': 1426, 'america': 706, 'chicago': 1187, 'last': 2711, 'september': 4033, 'oversee': 3286, 'the': 4476, 'operation': 3233, 'american': 707, 'farmers': 1994, 'continue': 1395, 'as': 797, 'working': 4851, 'tenants': 4450, 'part': 3322, 'profits': 3555, 'harvests': 2310, 'rice': 3879, 'corn': 1424, 'soybean': 4190, 'oranges': 3245, 'go': 2208, 'investors': 2572, 'rental': 3792, 'agriculture': 651, 'minis

In [54]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.33)

In [55]:
print(X_train.shape)
print(X_test.shape)

(134, 4909)
(66, 4909)


In [56]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors = 10, metric = "minkowski", p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [57]:
import numpy as np

y_pred = classifier.predict(X_test)
np.set_printoptions(precision = 2)

In [58]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
# Predicting on the test set
class_test_predictions = classifier.predict(X_test)
# Evaluation
print('Confusion Matrix')
print(confusion_matrix(y_test, class_test_predictions))
print()
print(classification_report(y_test, class_test_predictions))
print()
print('Accuracy :', '%.2f' % accuracy_score(y_test, class_test_predictions))

Confusion Matrix
[[22 11]
 [ 5 28]]

              precision    recall  f1-score   support

          -1       0.81      0.67      0.73        33
           1       0.72      0.85      0.78        33

    accuracy                           0.76        66
   macro avg       0.77      0.76      0.76        66
weighted avg       0.77      0.76      0.76        66


Accuracy : 0.76


In [63]:
newstest = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/testsetwithoutlabels.txt',sep='\t',names=['TITLE','DATE','BODY'])
newstest.head(2)

TITLE  \
0     USSR WHEAT BONUS OFFER SAID STILL UNDER DEBATE   
1   HAITIAN CANE PLANTERS PROTEST SUGAR MILL CLOSURE   

                          DATE  \
0        WASHINGTON, March 6 -   
1   PORT-AU-PRINCE, April 13 -   

                                                BODY  
0   The Reagan administration continues  to debat...  
1   About 2,000 sugar cane planters  marched to P...

In [64]:
def preprocess(text):
    tokens = word_tokenize(text)
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token.lower() not in stop_words]  # tokens = [token for token in tokens if len(token) >= 3]
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token.lower()) for token in tokens]
    return ' '.join(tokens)

In [65]:
newstest['BODY2'] = newstest['BODY'].apply(preprocess)
newstest.head(2)


TITLE  \
0     USSR WHEAT BONUS OFFER SAID STILL UNDER DEBATE   
1   HAITIAN CANE PLANTERS PROTEST SUGAR MILL CLOSURE   

                          DATE  \
0        WASHINGTON, March 6 -   
1   PORT-AU-PRINCE, April 13 -   

                                                BODY  \
0   The Reagan administration continues  to debat...   
1   About 2,000 sugar cane planters  marched to P...   

                                               BODY2  
0  reagan administration continues debate whether...  
1  2,000 sugar cane planter marched port-au-princ...

In [67]:
# Use the same vectorizer used for training set
Xtest = vectorizer.transform(newstest['BODY2'])
print(Xtest.toarray())
print(X.shape)
print(Xtest.shape)



[[0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(200, 4909)
(100, 4909)


In [68]:
predictions_test = classifier.predict(Xtest)
newstest['PREDICTED_CLASS'] = predictions_test
newstest.head(2)

print(predictions_test)

[ 1  1  1 -1  1  1 -1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1  1  1  1
 -1  1  1 -1  1  1  1  1 -1 -1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1
  1  1  1 -1  1  1  1 -1 -1  1  1  1  1  1  1  1  1  1  1  1  1 -1  1  1
  1  1  1  1  1 -1 -1 -1  1  1  1  1  1  1 -1  1  1  1  1  1  1  1  1  1
  1  1  1  1]
